### ISSUE TITLE
rr: Saving execution to trace directory

### ISSUE THREAD

**Issue by gaurav-patel1988** [spiral/roadrunner-laravel#109]
## Describe the bug

> When i run rr serve command it gives me this error message "**execve failed: 'serve' (or interpreter) not found (ENOENT)**" 

**my rr.yaml file content given below:**

```yaml
http:
  address: 127.0.0.1:8001
  ssl:
    # host and port separated by semicolon (default :443)
    address: :8000
    redirect: false
    cert: /home/tejal-gandhi/Desktop/ssl/apache.crt
    key: /home/tejal-gandhi/Desktop/ssl/apache.key

    h2c: false
    max_concurrent_streams: 128
  pool:
    num_workers: 0
    max_jobs: 500
    supervisor:
      exec_ttl: 30s
  static:
    dir: public
  middleware: ["static"]
  workers:
    pool:
      numWorkers: 1
      maxJobs:    1

server:
  command: "php ./vendor/bin/roadrunner-worker"

  env:
    - APP_ENV: production
    - APP_BASE_PATH: "/home/tejal-gandhi/Desktop/octane"
    - LARAVEL_OCTANE: "1"

rpc:
  listen: tcp://127.0.0.1:6001

logs:
  mode: production
  level: debug
  output: stdout
  encoding: json
```
