### ISSUE TITLE
How to set up Laravel public directory for assets?

### ISSUE THREAD

**Issue by ant100** [spiral/roadrunner-laravel#13]
Hi! For some reason, the route to Laravel's public directory (where all my assets are) is not being recognized. 

Currently all routes to assets inside the public directory are something like: 

`/css/main.css `

however this is returning a laravel 404 not found. I even tried to directly type:

`/public/css/main.css`

but got the same 404 not found page. This is laravel's page though, which is weird because it's a default application, the only thing I did was add a css subfolder inside of public folder.  

Got the exact same application running on Apache with no problem, so I figured this could be a RR configuration issue, maybe I need to set up the public directory in a config file somewhere?

**Comment by tarampampam** [comment]
Please, attach your configuration, rr/php/package versions, and your command to run rr daemon.

**Comment by ant100** [comment]
> Please, attach your configuration, rr/php/package versions, and your command to run rr daemon.

Yes, by configuration do you mean the .rr.yaml file? This is it:

```
env:
        #APP_REFRESH: true

http:
        address: 172.31.46.8:8080
        workers:
                command: 'php ./vendor/bin/rr-worker'

        static:
                dir: 'public'
```
Also, currently not running through daemon, testing it out first with 

`./rr -c ./.rr.yaml serve -d`

And versions: 

PHP: 7.4.8
RoadRunner: 1.8.2
RoadRunner-Laravel Package:  ^3.4
