### ISSUE TITLE
Issues with laravel url helper and port?

### ISSUE THREAD

**Issue by ant100** [spiral/roadrunner-laravel#14]
Hi guys

Just asking in case you happen to know about this. When configuring my application, I'm trying to make it work on port 8180, but for some reason the url helper is not recognizing the port, so for instance if I use route("tasks") the url I get is example.com/tasks instead of example.com:8180/tasks 

This doesn't happen when I try php artisan serve, the url shows correctly the 8000 port. It works fine on apache as well. Wondering if maybe there is some settings I'm missing.

My rr.yaml file is as following:

```
env:
        APP_REFRESH: true

http:
        address: 0.0.0.0:8180
        workers:
                command: 'php ./vendor/bin/rr-worker'

static:
        dir: 'public/'
```
And I've also set the url with port in app_url in the .env file. 

It works if I enter the url directly, it's just the helper that is not recognizing the port for some reason.
