### ISSUE TITLE
Service Container -> Binding A Singleton

### ISSUE THREAD

**Issue by nitrogenium** [spiral/roadrunner-laravel#90]
A clean installation of this repository, but:

.rr.local.yml
```yml
  # Workers pool settings.
  pool:
    # How many worker processes will be started. Zero (or nothing) means the number of logical CPUs.
    #
    # Default: 0
    num_workers: 2
```

**MyCounter.php**
```php
<?php

namespace App\Singleton;


use Illuminate\Support\Facades\Log;

class MyCounter
{

    protected int $counter=0;

    public function __construct()
    {
        Log::debug('MyCounter __construct');

    }

    public function __destruct ()
    {
        Log::debug('MyCounter __destruct');
    }

    public function increment(): int
    {
         Log::debug('++');
         return ++$this->counter;
    }

}

```

In AppServiceProvider

```php

    public function register()
    {
        $this->app->singleton('mc', function () {
            return new MyCounter();
        });
    }

```

In welcome.blade.php

```php
   {{ app()->make('mc')->increment() }}
```

In the log file each request:
```
[2022-02-21 06:10:56] local.DEBUG: MyCounter __construct
[2022-02-21 06:10:56] local.DEBUG: ++
[2022-02-21 06:10:56] local.DEBUG: MyCounter __destruct
```

**Obviously, the counter is reset every time.
Why? What am I doing wrong?**

What power kills my singleton "mc"?
